spring.application.name=api-gateway
server.port=8765
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*

uri=lb://QUIZ-SERVICE

#spring.cloud.gateway.mvc.routes[0].id=quiz
#spring.cloud.gateway.mvc.routes[0].uri=lb://QUIZ-SERVICE
#spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/quiz-service/**
#spring.cloud.gateway.mvc.routes[0].filters[0]=StripPrefix=1
management.endpoint.gateway.enabled=true